mode:
  open:    true
  backend: true

language:
  lang: "zh-CN"
  path: "resource/i18n"

server:
  address:       ""                             # 本地监听地址。默认":80"，多个地址以","号分隔。
  httpsAddr:     ":443"                         # TLS/HTTPS配置，同时需要配置证书和密钥。默认关闭。配置格式同上。
  httpsCertPath: "manifest/config/server.crt"   # TLS/HTTPS证书文件本地路径，建议使用绝对路径。默认关闭
  httpsKeyPath:  "manifest/config/server.key"   # TLS/HTTPS密钥文件本地路径，建议使用绝对路径。默认关闭

  openapiPath: "/api.json"
  swaggerPath: "/swagger"

  serverRoot: "resource/front"

  # 日志基本配置
  logPath:             "logs/server"      # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout:           true               # 日志是否输出到终端。默认为true
  errorStack:          true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  errorLogEnabled:     true               # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern:     "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled:    true               # 是否记录访问日志。默认为false
  accessLogPattern:    "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

  # 日志扩展配置
  logger:
    path:                 ""              # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file:                 "{Y-m-d}.log"   # 日志文件格式。默认为"{Y-m-d}.log"
    prefix:               ""              # 日志内容输出前缀。默认为空
    level:                "all"           # 日志输出级别
    stdout:               true            # 日志是否同时输出到终端。默认true
    rotateSize:           0               # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateExpire:         0               # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit:    0               # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire:   0               # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupCompress: 0               # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
    rotateCheckInterval:  "1h"             # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时

  open:
    authExpire:    6                              # 认证时间窗口
    address:       ""                             # 本地监听地址。默认":80"，多个地址以","号分隔。
    httpsAddr:     ":4431"                        # TLS/HTTPS配置，同时需要配置证书和密钥。默认关闭。配置格式同上。
    httpsCertPath: "manifest/config/server.crt"   # TLS/HTTPS证书文件本地路径，建议使用绝对路径。默认关闭
    httpsKeyPath:  "manifest/config/server.key"   # TLS/HTTPS密钥文件本地路径，建议使用绝对路径。默认关闭

    logPath:           "logs/open"        # High
    logStdout:         false              # 废弃
    errorStack:        true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    errorLogEnabled:   true               # 是否记录异常日志信息到日志中。默认为true
    errorLogPattern:   "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    accessLogEnabled:  true               # 是否记录访问日志。默认为false
    accessLogPattern:  "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

    logger:
      path:   ""             # Low
      file:   "{Y-m-d}.log"
      prefix: ""
      level:  "all"
      stdout: true

logger:
  path:   "logs"
  level : "all"
  stdout: false

database:
  logger:
    path:   "logs/sql"
    level:  "all"
    stdout: true
  default:
    - link:       "mysql:${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql-server:3306)/tinyscan?loc=Local&parseTime=true"
      maxIdle:     10
      maxOpen:     30
      maxLifetime: 30
      debug:       true
      dryRun:      0

mongodb:
  host:     "mongo-server"
  port:     27017
  user:     "${MONGO_USER}"
  password: "${MONGO_PASSWORD}"

