version: "3.7"
services:
    engine-server:
        image: registry.cn-beijing.aliyuncs.com/tinyscan/ubuntu-base:tinyscan-engine_v4
        restart: always
        container_name: tinyscan-engine
        privileged: true
        working_dir: /app
        command: /export/bin/sScan -f /export/conf/config.ini
        environment:
            - LANG=C.UTF-8
            - AUTH_CODE=${AUTH_CODE}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/tinyscan/engine/app:/app"
            - "/tinyscan/engine/export:/export"
        depends_on:
            - mongo-server
        networks:
            - tinyscan
networks:
    tinyscan:
